import { ClerkProvider } from '@clerk/nextjs';

import { GetCal } from '@bxav/ui-saas-components';
import { Toaster } from '@bxav/ui-components';

import './global.css';

export const metadata = {
  title: 'Welcome to playground',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body>
          {children}
          <GetCal calLink="bxav1/15min" />
        </body>
        <Toaster />
      </html>
    </ClerkProvider>
  );
}
