contentAreas:
  readme:
    pattern: .md
    voiceAndEthos: ./.contentcrafter/readme/voice-and-ethos.md
#    templates:
#      - path: ./.contentcrafter/docs/template.md
#    examples:
#      - path: ./example.md
