import { ClerkProvider } from '@clerk/nextjs';

import './global.css';

export const metadata = {
  title: 'Welcome to assistants',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body>{children}</body>
      </html>
    </ClerkProvider>
  );
}
